### PR TITLE
Brandon

### PR DESCRIPTION
**Pull request by brandonMccoy**

### CODE REVIEW

**Comment by ptmdmusique** [comment]
Can you add some juicy gif or image ❓ 👁️

**Comment by brandonMccoy** [comment]
There should be already be a large image of a dragon that loads onto the Home page. Or should I add something else?
dandd-br-1564600399165

**Comment by ptmdmusique** [comment]
Ah sorry, I meant the image or gif of how the website looks like for this PR. In my opinion, that way it would help people to have a rough understanding of what you're doing without having to pull the branch down and run it

**Comment by brandonMccoy** [comment]
Screenshot 2021-03-11 173207

**Comment by ptmdmusique** [comment]
Noice dude! Good work 🎉

**Review by ptmdmusique — APPROVED** [review]

**Pull request merged**
